### ISSUE TITLE
[go1.13.x] Error handling TestMain logic

### ISSUE THREAD

**Issue by ofek** [gotestyourself/gotestsum#101]
If `TestMain` exits 0 (or just returns) and no tests are executed, the package will show as failed. See: https://github.com/DataDog/datadog-agent/pull/5294

```go
func TestMain(m *testing.M) {
	if _, ok := os.LookupEnv("INTEGRATION"); !ok {
		log.Println("--- SKIP: to run tests in this package, set the INTEGRATION environment variable")
		os.Exit(0)
	}
	os.Exit(m.Run())
}
```

```
=== Failed
=== FAIL: pkg/trace/test/testsuite  (0.00s)
2020/04/15 15:35:55 --- SKIP: to run tests in this package, set the INTEGRATION environment variable
ok  	github.com/DataDog/datadog-agent/pkg/trace/test/testsuite	1.015s
```

**Comment by dnephin** [comment]
Thank you for the bug report! I tried this out with a test file that only contained the example you provied and wasn't able to reproduce the issue:

```
$ gotestsum ./tmp3
✓  tmp3 (1ms)

DONE 0 tests in 0.153s

$ gotestsum -f short-verbose ./tmp3
2020/04/15 12:17:31 --- SKIP: to run tests in this package, set the INTEGRATION environment variable
PASS tmp3

DONE 0 tests in 0.148s

$ gotestsum -f standard-verbose ./tmp3
2020/04/15 12:17:38 --- SKIP: to run tests in this package, set the INTEGRATION environment variable
ok      gotest.tools/gotestsum/tmp3     0.001s

DONE 0 tests in 0.151s
```

I don't think `gotestsum` ever creates output that mimics the `go test` output (ex: the `=== Failed`, `=== FAIL: ...`). It always uses the output from `gotest -json`. I suspect this failed message is coming from `go test`, but I'm not sure why.

Are you able to reproduce with `go test -v` ?

**Comment by ofek** [comment]
Just tried `go test -v`:

```
=== RUN   TestSafeBuffer
--- PASS: TestSafeBuffer (0.00s)
PASS
ok      github.com/DataDog/datadog-agent/pkg/trace/test (cached)
2020/04/15 12:54:12 --- SKIP: to run tests in this package, set the INTEGRATION environment variable
ok      github.com/DataDog/datadog-agent/pkg/trace/test/testsuite       0.045s
=== RUN   TestRandomBucket
--- PASS: TestRandomBucket (0.00s)
=== RUN   TestTestBucket
--- PASS: TestTestBucket (0.00s)
PASS
ok      github.com/DataDog/datadog-agent/pkg/trace/test/testutil        (cached)
=== RUN   TestTopLevelTypical
--- PASS: TestTopLevelTypical (0.00s)
```

**Comment by dnephin** [comment]
That is strange! Which version of Go? Do you have a link to a CI job where this failed?

**Comment by ofek** [comment]
- https://app.circleci.com/pipelines/github/DataDog/datadog-agent/171/workflows/c3138d6c-b27f-4285-b7d6-131153c10694/jobs/210535
- https://circleci.com/api/v1.1/project/github/DataDog/datadog-agent/210535/output/103/0?file=true

The line-by-line package status is different too

## go test

passes

--- Running unit tests:
go test  -vet=off -timeout 120s -tags "zlib fargateprocess consul process zk ec2 apm docker gce secrets kubeapiserver orchestrator clusterchecks etcd jmx python kubelet dovet test" -gcflags="" -ldflags="-X github.com/DataDog/datadog-agent/pkg/version.Commit=ac052a8b5 -X github.com/DataDog/datadog-agent/pkg/version.AgentVersion=7.19.0-rc.5+git.5.ac052a8 -X github.com/DataDog/datadog-agent/pkg/serializer.AgentPayloadVersion=4.30.0 -X github.com/DataDog/datadog-agent/pkg/config.ForceDefaultPython=true -X github.com/DataDog/datadog-agent/pkg/config.DefaultPython=3 "   -short    ./pkg/trace/...
ok      github.com/DataDog/datadog-agent/pkg/trace/agent        (cached)
ok      github.com/DataDog/datadog-agent/pkg/trace/api  (cached)
?       github.com/DataDog/datadog-agent/pkg/trace/atomic       [no test files]
ok      github.com/DataDog/datadog-agent/pkg/trace/config       (cached)
ok      github.com/DataDog/datadog-agent/pkg/trace/event        (cached)
ok      github.com/DataDog/datadog-agent/pkg/trace/filters      (cached)
?       github.com/DataDog/datadog-agent/pkg/trace/flags        [no test files]
ok      github.com/DataDog/datadog-agent/pkg/trace/info (cached)
ok      github.com/DataDog/datadog-agent/pkg/trace/logutil      (cached)
?       github.com/DataDog/datadog-agent/pkg/trace/metrics      [no test files]
ok      github.com/DataDog/datadog-agent/pkg/trace/metrics/timing       (cached)
ok      github.com/DataDog/datadog-agent/pkg/trace/obfuscate    (cached)
?       github.com/DataDog/datadog-agent/pkg/trace/osutil       [no test files]
ok      github.com/DataDog/datadog-agent/pkg/trace/pb   (cached)
ok      github.com/DataDog/datadog-agent/pkg/trace/sampler      (cached)
ok      github.com/DataDog/datadog-agent/pkg/trace/stats        (cached)
ok      github.com/DataDog/datadog-agent/pkg/trace/stats/quantile       (cached)
ok      github.com/DataDog/datadog-agent/pkg/trace/test (cached)
ok      github.com/DataDog/datadog-agent/pkg/trace/test/testsuite       0.043s
ok      github.com/DataDog/datadog-agent/pkg/trace/test/testutil        (cached)
ok      github.com/DataDog/datadog-agent/pkg/trace/traceutil    (cached)
ok      github.com/DataDog/datadog-agent/pkg/trace/watchdog     (cached)
ok      github.com/DataDog/datadog-agent/pkg/trace/writer       (cached)```
```

## gotestsum

fails (a big X)

```
--- Running unit tests:
gotestsum --format pkgname --  -vet=off -timeout 120s -tags "apm fargateprocess jmx zlib kubelet consul process kubeapiserver ec2 zk gce secrets python etcd docker orchestrator clusterchecks dovet test" -gcflags="" -ldflags="-X github.com/DataDog/datadog-agent/pkg/version.Commit=ac052a8b5 -X github.com/DataDog/datadog-agent/pkg/version.AgentVersion=7.19.0-rc.5+git.5.ac052a8 -X github.com/DataDog/datadog-agent/pkg/serializer.AgentPayloadVersion=4.30.0 -X github.com/DataDog/datadog-agent/pkg/config.ForceDefaultPython=true -X github.com/DataDog/datadog-agent/pkg/config.DefaultPython=3 "   -short    ./pkg/trace/...
✓  github.com/DataDog/datadog-agent/pkg/trace/filters (cached)
✓  github.com/DataDog/datadog-agent/pkg/trace/metrics/timing (cached)
✓  github.com/DataDog/datadog-agent/pkg/trace/event (cached)
✓  github.com/DataDog/datadog-agent/pkg/trace/test/testutil (cached)
✓  github.com/DataDog/datadog-agent/pkg/trace/test (cached)
✓  github.com/DataDog/datadog-agent/pkg/trace/watchdog (cached)
✓  github.com/DataDog/datadog-agent/pkg/trace/info (cached)
✓  github.com/DataDog/datadog-agent/pkg/trace/sampler (cached)
✓  github.com/DataDog/datadog-agent/pkg/trace/writer (cached)
✓  github.com/DataDog/datadog-agent/pkg/trace/stats (cached)
✓  github.com/DataDog/datadog-agent/pkg/trace/agent (cached)
✓  github.com/DataDog/datadog-agent/pkg/trace/obfuscate (cached)
✓  github.com/DataDog/datadog-agent/pkg/trace/api (cached)
∅  github.com/DataDog/datadog-agent/pkg/trace/atomic
✓  github.com/DataDog/datadog-agent/pkg/trace/config (cached)
∅  github.com/DataDog/datadog-agent/pkg/trace/flags
✓  github.com/DataDog/datadog-agent/pkg/trace/stats/quantile (cached)
✓  github.com/DataDog/datadog-agent/pkg/trace/logutil (cached)
∅  github.com/DataDog/datadog-agent/pkg/trace/metrics
∅  github.com/DataDog/datadog-agent/pkg/trace/osutil
✓  github.com/DataDog/datadog-agent/pkg/trace/pb (cached)
✓  github.com/DataDog/datadog-agent/pkg/trace/traceutil (cached)
✖  github.com/DataDog/datadog-agent/pkg/trace/test/testsuite (45ms)

=== Skipped
=== SKIP: github.com/DataDog/datadog-agent/pkg/trace/agent TestEventProcessorFromConf (0.00s)
    agent_test.go:347: set INTEGRATION environment variable to run

=== SKIP: github.com/DataDog/datadog-agent/pkg/trace/agent TestEventProcessorFromConfLegacy (0.00s)
    agent_test.go:396: set INTEGRATION environment variable to run

=== SKIP: github.com/DataDog/datadog-agent/pkg/trace/logutil TestThrottled (0.00s)
    throttled_test.go:16:


=== Failed
=== FAIL: github.com/DataDog/datadog-agent/pkg/trace/test/testsuite  (0.00s)
2020/04/15 13:20:45 --- SKIP: to run tests in this package, set the INTEGRATION environment variable
ok      github.com/DataDog/datadog-agent/pkg/trace/test/testsuite       0.045s


DONE 751 tests, 3 skipped, 1 failure in 1.204s
```

**Comment by ofek** [comment]
Go 1.13.8

**Comment by dnephin** [comment]
When I run `go test -json` with go1.13.8 I see:

```
{"Time":"2020-04-15T18:07:21.50727715Z","Action":"fail","Package":"github.com/DataDog/datadog-agent/pkg/trace/test/testsuite","Test":"to run tests in this package, set the INTEGRATION environment variable","Elapsed":0.021}
```

The json TestEvent (which gotestsum uses) is reported the package as failed, and for some reason it is parsing the output as the test name.

This appears to be a bug in `test2json` that is fixed in go1.14.x. In go1.14.x the json output reports correctly.

**Comment by ofek** [comment]
Ah wow, great debugging!!!

**Comment by dnephin** [comment]
This bug is fixed in go in the last few releases, so I'm going to close this issue.
