### ISSUE TITLE
When go test -count is greater than 1, only the output for the last test is saved.

### ISSUE THREAD

**Issue by dnephin** [gotestyourself/gotestsum#119]
If the test is not deterministic, and the last instance passed, then none of the output is saved because the output of passed tests is dropped from the buffer.

Also an issue if `ScanTestOutput` is passed the output from different runs, and the same test name is repeated in the output.

The problem is that output is saved in a map by test name. The same test can run twice, so this is not the correct index. I think the solution is to assign a unique id to each TestCase. Output can be saved, and looked up by id.

**Comment by viralkpanchal** [comment]
Hi,

I have a MAKE file that looks like below:
```
GOGETTESTSUM=go get gotest.tools/gotestsum

GOTESTSUM_JSONFILE=gotestsum --jsonfile test-output.log

all: product1_region_uat product2_region_uat product3_region_uat

product1_region_uat:
$(GOGETTESTSUM)
parameters product1_test $(GOTESTSUM_JSONFILE)

product2_region_uat:
$(GOGETTESTSUM)
parameters product2_test $(GOTESTSUM_JSONFILE)

product3_region_uat:
$(GOGETTESTSUM)
parameters product3_test $(GOTESTSUM_JSONFILE)
```
Each time I execute tests using `make all` to capture test outcome in `test-output.log` file, result of only the last executed test suite is getting saved (i.e. product3 in this instance).

How can I save test execution for all 3 test suites?

**Comment by dnephin** [comment]
Hello @viralkpanchal, thanks for your interest in `gotestsum`!

I think the problem you are seeing is that `gotestsum` is being run 3 times by the makefile. Every time `gotestsum` runs it will override the `--jsonfile`. I think you could fix the problem by having a target run all the packages at once, instead of one at a time, or you could use a different filename for each package. `make` has some fancy syntax for getting the name of the currently run target, which you could use as part of the jsonfile name. I don't remember exactly what that looks like.

Generally the idea is that running a single `gotestsum` invocation would be preferable. It is possible that `--jsonfile` could be made to append to the file, instead of overriding it. Or a new flag could be added to do append instead of override. I'm not sure if that is really the right solution, and would need to think about it some more. I think we could create a new issue for that change, as it is not exactly related to this problem.

I hope that helps!
