### ISSUE TITLE
Go1.14: junit test result contains unrelated error message from t.Log

### ISSUE THREAD

**Issue by chaodaiG** [gotestyourself/gotestsum#128]
Starting go1.14, `t.Log` starts to stream during test run instead of at the end, this has caused interleaved logs when `t.Parallel` is configured, thus the error messages in junit results contain lots of unrelated logs from other tests. 

See an example here: https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_serving/8274/pull-knative-serving-integration-tests/1270397344797429763

**Comment by dnephin** [comment]
Thank you for the bug report!

This is an issue in go1.14, see https://github.com/golang/go/issues/38458. It was fixed recently, so it should be resolved in go1.15.  I wasn't able to find any way to work around the issue.

**Comment by chaodaiG** [comment]
Great to know. Thanks for the pointer!

**Comment by dnephin** [comment]
So far Go 1.15 and 1.16 seem to be working well, so I'm going to close this issue now.
