### ISSUE TITLE
Please consider bugfix release

### ISSUE THREAD

**Issue by naisuuuu** [gotestyourself/gotestsum#130]
Hi, I'm using the testjson package and ran into unexpected panics while calling `ScanTestOutput` with nil `ScanConfig.Handler`. After some confusion, I realized I'm looking at the master branch code, 50 something commits ahead of latest release and with the underlying bug fixed.

Is something in the way of v0.4.3? I'd be glad to help if I can! Importing from master for now, but that's ugly.

**Comment by dnephin** [comment]
Hello, and thank you for your interest in `gotestsum`!  I should be doing a v0.5.0 release soon, I think all that is missing is a few more docs for the latest features (#117)

**Comment by dnephin** [comment]
https://github.com/gotestyourself/gotestsum/releases/tag/v0.5.0
