### ISSUE TITLE
go get gotestsum fails (GOPATH mode)

### ISSUE THREAD

**Issue by etcher123** [gotestyourself/gotestsum#131]
Doing some tests with `goteststum`. In GOPATH mode I can't get gotestsum.

```
$ docker run --rm -it golang

# printenv | grep GO
GOLANG_VERSION=1.14.4
GOPATH=/go

# pwd
/go

# go get gotest.tools/gotestsum/...
package gotest.tools/gotestsum/internal/text
	imports gotest.tools/v3/assert: /go/src/gotest.tools exists but /go/src/gotest.tools/.git does not - stale checkout?

# ls src/gotest.tools/
gotestsum
```

**Comment by elboulangero** [comment]
(note: I reported this issue, however with another github login, but it's me all the same)

So obviously I can workaround by setting up everything manually, ie. something like:

```
cd src
mkdir gotest.tools
cd gotest.tools
git clone https://github.com/gotestyourself/gotest.tools.git v3
git clone  https://github.com/gotestyourself/gotestsum.git gotestsum
```

**Comment by dnephin** [comment]
Thank you for the bug report! I haven't used GOPATH in a while, and I'm not sure exactly how it is supposed to work now with import aliases.

I think it should be pretty safe to remove the import aliases from this project. I'll give that a try to see if it work.

**Comment by dnephin** [comment]
I just tried this (and with the ubuntu `golang` image as well):

```
$ docker run --rm -it golang:alpine
# go version
go version go1.14.4 linux/amd64
# apk add --no-cache git
# go get gotest.tools/gotestsum
# gotestsum --version
gotestsum version master
```

That seems to work. Maybe it was the trailing `/...` that was breaking `go get` ?

**Comment by dnephin** [comment]
Looking at this issue again, I can confirm the problem was the trailing `/...`.  Installing using `go get gotest.tools/gotestsum` continues to work.
