### ISSUE TITLE
Is this a schema error?

### ISSUE THREAD

**Issue by peterfeifanchen** [gotestyourself/gotestsum#138]
https://github.com/gotestyourself/gotestsum/blob/master/internal/junitxml/report.go#L21

Shouldn't it be `Suites  []JUnitTestSuite `xml:"testsuite"``. I just tried to read XML with this schema and without this it would only read the outside testsuites tags.

**Comment by dnephin** [comment]
hmm, I'm honestly not too sure. I haven't worked with encoding/xml all that much, and it has been a while. In `gotestsum` the types are only used to write out an xml document, never to read one, so it is quite possible that some tags are missing for reading.

**Comment by peterfeifanchen** [comment]
I guess there is no need for fix it for now? Since it is in an internal package and junitxml doesnt exactly need to read xml, just output it.
