### ISSUE TITLE
short-verbose is the example, but not listed in the "list of formats"

### ISSUE THREAD

**Issue by ghostsquad** [gotestyourself/gotestsum#139]
```
Format

Set a format with the --format flag or the GOTESTSUM_FORMAT environment variable.

gotestsum --format short-verbose

Supported formats:

    dots - print a character for each test.
    pkgname (default) - print a line for each package.
    pkgname-and-test-fails - print a line for each package, and failed test output.
    testname - print a line for each test and package.
    standard-quiet - the standard go test format.
    standard-verbose - the standard go test -v format.
```

Notice how `short-verbose` is in the example of how to run, but it's not in the list below with an explanation of what is printed with it.

**Comment by dnephin** [comment]
Ah yes, thank you for the report! `short-verbose` was changed to `testname` and it looks like I didn't update the README correctly. Fixed in e076327

**Comment by ghostsquad** [comment]
hmm, what am I doing wrong?

```
12:41:42 in seaworthy on  main [!+] via 🐹 v1.14.4
❯ go install gotest.tools/gotestsum

12:41:50 in seaworthy on  main [!+] via 🐹 v1.14.4
❯ which gotestsum
/Users/wmcnamee/go/bin/gotestsum

12:41:54 in seaworthy on  main [!+] via 🐹 v1.14.4
❯ make test
gotestsum --format testname ./...
gotestsum: Error: unknown format testname
```

**Comment by ghostsquad** [comment]
`go install` seems to not be doing the right thing. but `go get -u` worked.

**Comment by dnephin** [comment]
The formats were renamed in v0.4.1. The old names work, but the new names won't in versions before that. I think `go install` only installs from `GOPATH` or an active module directory, it doesn't download from github.

So I think what might be happening is that you have an older version of `gotestsum` checked out in the Go path, and `go install` installed that.

**Comment by ghostsquad** [comment]
ah ok. thanks!
