### ISSUE TITLE
testname format without logs output

### ISSUE THREAD

**Issue by alufrew** [gotestyourself/gotestsum#167]
Hi! 

I try to use testname format for showing tests during running. The problem is I run tests in parallel. If one test fails it's marked as failed and all output is shown. But because of parallel there can be api cals from other not related tests. It looks like this:

```
PASS test.TestOtherApi (1.81s)
2020/11/25 15:46:11 GET          https://some.api/other_not_related api
2020/11/25 15:46:11 GET          https://some.api/api
    some_api_test.go:45: 
                Error Trace:    some_api_test.go:45
                                                        some_api_test.go:15
                Error:          Should not be: 200
                Test:           TestSomeApi
--- FAIL: TestSomeApi (1.81s)
FAIL test.TestSomeApi (1.81s)
```
Is there possibility to print test names only with their status PASS/FAIL/SKIPPED but without full verbose output? Somewhat like this:

```
PASS test.TestOtherApi (1.81s)
FAIL test.TestSomeApi (1.81s)
```

**Comment by dnephin** [comment]
Thank you for the bug report! This was a problem with some versions of `go1.14.x` but it should have been fixed in go1.15. Which version of Go are you using?

**Comment by dnephin** [comment]
A new format that only prints the name would also be possible. Wouldn't that make it hard to debug the test failures if there is no output?

**Comment by alufrew** [comment]
Hi. Currently I am using go1.15.
I am still investigating workarounds. Maybe the reason is that my logging before using parallel was pretty strait forward - log.Println(). I will try to use t.log() next. Maybe it will help. 

> A new format that only prints the name would also be possible. Wouldn't that make it hard to debug the test failures if there is no output?

Unfortunately it's harder now. Because in parallel logs from different test cases mess up real test case flow. I was planning to parse json at the end of test to correctly show logs for failed test. But maybe update to go 1.15.x will help.

**Comment by dnephin** [comment]
Another strategy I've seen used to fix this problem is to send all the logs to a `bytes.Buffer`, and use something like this to only prints the logs if a test fails:

```
buf := bytes.Buffer()
logger.SetOutput(buf)
t.Cleanup(func() {
    if t.Failed() {
        t.Log(buf.String())
    }
})
```

That should prevent overlap because all the logs are printed at once at the end, and logs for passing tests can't get mixed in.

**Comment by alufrew** [comment]
Hi. Changing logs to t.log() helped. Thank you fro your time.
