### ISSUE TITLE
watch: bad file descriptor

### ISSUE THREAD

**Issue by docwhat** [gotestyourself/gotestsum#171]
The `--watch` flag doesn't work for me.

```sh
$ ~/go/bin/gotestsum --watch ./...
Watching 61 directories. Use Ctrl-c to to stop a run or exit.
ERROR bad file descriptor
```

I've tried the v0.6.0 from the release page and using `go get` as well.  The OS is macOS Big Sur.

**Comment by dnephin** [comment]
Thank you for the bug report! 

Do you get this error on every directory? If you try watching on a sub directory that doesn't have any other sub directories does it work, or does the problem happen on every directory? I suspect there is one (or a small number of) file(s) under this directory which are causing the problem. 

I'll add some error wrapping to provide more information (at the very least a filename). It might make sense to also consider these warnings instead of errors.

**Comment by docwhat** [comment]
> Thank you for the bug report!

Glad to help!

> Do you get this error on every directory?
> If you try watching on a sub directory that doesn't have any other sub directories does it work, or does the problem happen on every directory?
> I suspect there is one (or a small number of) file(s) under this directory which are causing the problem.

I tracked it down to something in my `pkg` sub-directory.   Still a lot of code (61 directories).

I tried this:

```sh
for i in **/*_test.go; do rm -fv "$i"; gotestsum --watch && break; done
```

But even with all `*_test.go` files gone, it still goes boom: `ERROR bad file descriptor`

Next I tried deleting all `*.go` files one by one:

```sh
$ for i in **/*.go; do rm -fv "$i"; gotestsum --watch ./... && break; done
...
foo/bar.go
Watching 25 directories. Use Ctrl-c to to stop a run or exit.
ERROR fcntl: too many open files
foo/baz.go
Watching 25 directories. Use Ctrl-c to to stop a run or exit.
^C
```

Hah! it works!

It looks like it is a "too many files" problem.

I have 415 `.go` files in 252 directories.

```sh
$ limit
cputime         unlimited
filesize        unlimited
datasize        unlimited
stacksize       8MB
coredumpsize    0kB
addressspace    unlimited
memorylocked    unlimited
maxproc         2784
descriptors     256
```

It now works if I bump up the number of file descriptors:

```sh
$ limit descriptors 1024
$ gotestsum --watch
Watching 61 directories. Use Ctrl-c to to stop a run or exit.
...
```

I haven't dug trough your code yet, but I'm guessing you're keeping descriptors open for all the files that may change.

macOS has a nice mechanism that lets you get events for directory and it's children without having lots of file open.

> I'll add some error wrapping to provide more information (at the very least a filename). It might make sense to also consider these warnings instead of errors.

Cool!

**Comment by dnephin** [comment]
Thank you again for tracking this down! As you discovered in #173 there was a missing close on a file handle which leaked some file handles and cause the process to hit the limit. I'm adding some more error wrapping in #174.
