### ISSUE TITLE
Binary for Apple Silicon

### ISSUE THREAD

**Issue by ProjectFrank** [gotestyourself/gotestsum#186]
This will require go 1.16

**Comment by ProjectFrank** [comment]
It looks like this project already uses go 1.16 in CI and builds using the latest version of goreleaser. Now that goreleaser supports darwin-arm64, this should just work by rerunning the CI pipeline.

**Comment by dnephin** [comment]
I tagged v1.6.3, but the release job is broken because of a checkout key. I'll have to fix that in a bit.

**Comment by dnephin** [comment]
https://github.com/gotestyourself/gotestsum/releases/tag/v1.6.3

**Comment by ProjectFrank** [comment]
Thanks for the quick response @dnephin 😄
