### ISSUE TITLE
Document feature to convert "go test" json output to junit xml without invoking "go test"

### ISSUE THREAD

**Issue by rodrigc** [gotestyourself/gotestsum#19]
gotestsum right now invokes `go test` under the hood, and allows you to generate an output json file or an output JUnit xml file directly.

This is very handy.

I have some use cases where I cannot install gotestsum in the environment where I am running the tests.  However, I can:

1.  Run `go test` and generate the output json file
2. Copy this json file somewhere else
3. Run a postprocessor on the json file, and generate the XML file

If you keep the existing behavior of gotestsum, but could add this additional behavior,
that would be very handy.  For example, something like:

```
gotestsum convert --input testresults.json --junitxml testresults.xml
```

This behavior I am requesting is similar to https://github.com/jstemmer/go-junit-report, but go-junit-report does not parse JSON as input.....it parses the raw `go test` output.  Parsing JSON is better.

**Comment by rodrigc** [comment]
I verified that this worked for me:

```
gotestsum --junitfile testresults.xml --raw-command cat testoutput.json
```

If you want to add this as an example to the docs, that would be helpful.

Longer term, if you want to add an option to read from stdin or from an existing file that would be also helpful too.

**Comment by mpictor** [comment]
I'd like to have the `go test -json` parsing and junit writing as importable package(s) with minimal deps, so I can vendor it without pulling in all the deps necessary for the pretty human-readable output (logrus, color, etc etc etc). Then I can import it into a magefile, and with a couple lines of code have the test output formatted for CI.
