### ISSUE TITLE
Tag a v1.7.0 release

### ISSUE THREAD

**Issue by thaJeztah** [gotestyourself/gotestsum#206]
When looking in the containerd repository, I noticed it was using a non-tagged version of gotestsum (see https://github.com/containerd/containerd/pull/5754)

Looking through the changes since the last release; https://github.com/gotestyourself/gotestsum/compare/v1.6.4...1a9438079330f60c1301fdfacafbfac8763214a5, there's some bugfixes, and at least one new feature (`--ignore-non-json-output-lines`, added in https://github.com/gotestyourself/gotestsum/pull/194). so (to try to follow SemVer) would warrant a "minor" version update (v1.7.0).

Wondering if there's plans to do a new release?

/cc @dnephin @vdemeester

**Comment by dnephin** [comment]
Done! https://github.com/gotestyourself/gotestsum/releases/tag/v1.7.0

**Comment by thaJeztah** [comment]
Thanks!
