### ISSUE TITLE
Run all tests in watch mode is not working

### ISSUE THREAD

**Issue by robsonpeixoto** [gotestyourself/gotestsum#207]
When I press `a` in watch mode nothin happens.
And the `l` doesn't have a useful output.

Thanks for this amazing tool :)

**Comment by dnephin** [comment]
Thanks for reporting this issue! I believe the problem is that these two features were added after the last release. It should work with the code in the main branch. We need to do a 1.7.0 release soon (#206).

**Comment by dnephin** [comment]
Done! https://github.com/gotestyourself/gotestsum/releases/tag/v1.7.0

Let me know if it still does not work with the latest release

**Comment by robsonpeixoto** [comment]
It's working very well. Thanks @dnephin.
Just a suggestion, add a `?` command to show a simple help.

**Comment by dnephin** [comment]
Thanks, I think that's a good suggestion! I've added that command in #211
