### ISSUE TITLE
Passing tests reported as failures when using godog junit format

### ISSUE THREAD

**Issue by Samfucious** [gotestyourself/gotestsum#218]
The junit xml appears to be malformed.

✓  . (196ms)

=== Failed
=== FAIL: . TestMain (unknown)
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Functional BBD" tests="0" skipped="0" failures="0" errors="0" time="0.000013907"></testsuites>--- PASS: TestMain (0.00s)

DONE 4 tests, 1 failure in 0.633s
[testlib_test.go.txt](https://github.com/gotestyourself/gotestsum/files/7328836/testlib_test.go.txt)

[testlib.go.txt](https://github.com/gotestyourself/gotestsum/files/7328837/testlib.go.txt)

**Comment by dnephin** [comment]
It sounds like this is expected (because the output from `godog` is not json), or a bug in `godog` not producing the correct json. I'm going to close this issue since it seems there is nothing to fix in `gotestsum`. Please comment if I've misunderstood and there is a problem to fix here.
