### ISSUE TITLE
how to pass -count=1 for go test using gotestsum?

### ISSUE THREAD

**Issue by kokizzu** [gotestyourself/gotestsum#230]
it seems cached test that should be failed detected as success if we don't pass that.

**Comment by dnephin** [comment]
Thanks for the question! The README attempts to document this here: https://github.com/gotestyourself/gotestsum#custom-go-test-command. The examples use `-tags`, but you can do the same thing with `-count=1.

I run tests this way regularly:
```
gotestsum -f testname -- -count=1 ./...
```
