### ISSUE TITLE
ability to force-create path where junit file must be created

### ISSUE THREAD

**Issue by glebsts** [gotestyourself/gotestsum#238]
Hello,
Thank you for nice tool!

Do you accept PRs? :)
I'd like to make gostest sum force create full path for junit file if given as `--junitfile foo/bar/tests.xml`. 
Whyt, should it be separate option or default behavior?

**Comment by dnephin** [comment]
Thank you for opening this issue! This is a great idea, I wish I had thought of it! I've had to `mkdir` in CI config before, and this change would have removed the need for that.

I am happy to accept PRs! I was doing some work in this repo so I decided to implement this myself in #241, but if you ever want to submit a PR for something else, please do!
