### ISSUE TITLE
Passing args to post run command 

### ISSUE THREAD

**Issue by TripleC1986** [gotestyourself/gotestsum#239]
Hello, I am using gotestsum to run my tests and the postruncommand to parse the junitxml.dule produced. The binary execution is working, but I was wondering if there is anyway to pass args to the post run binary. I have tried with no success, any help would be appreciated.

**Comment by TripleC1986** [comment]
https://github.com/gotestyourself/gotestsum/blob/73868edd232e5a2c571769ca402712a14ae58afe/cmd/handler.go#L105  looks like you can but I get parsing errors when trying to run gotestsum --post-run-command command --param=value

**Comment by dnephin** [comment]
Thank you for opening this issue! Looking at the docs I notice we don't have any example of passing multiple args or other flags to `--post-run-command`.  I'll get the docs updated.

If you provide the full error message I can help debug, but this seems to work for me:

```
gotestsum --debug --post-run-command "post-run --foo --bar"
```

As long as the full command is quoted the flags should get passed to the post run command properly.

**Comment by TripleC1986** [comment]
That makes sense, I wasn't wrapping the post run command in double quotes. Closing... Thanks for updating the docs.
