### ISSUE TITLE
Unable to install on AIX 7.2

### ISSUE THREAD

**Issue by knmiecc** [gotestyourself/gotestsum#244]
Hello everyone,

my environment is:
OS: AIX 7.2
go version: go version go1.16.12 aix/ppc64

**Problem**:
When I try to install gotestsum with either of the suggested install methods `go install gotest.tools/gotestsum@latest` or `go get gotest.tools/gotestsum`, it results in the following errors:

```
$ go get -v gotest.tools/gotestsum 
[...]
gotest.tools/gotestsum/internal/filewatcher
# gotest.tools/gotestsum/internal/filewatcher
pkg/mod/gotest.tools/gotestsum@v1.8.0/internal/filewatcher/term_unix.go:43:40: undefined: tcGet
pkg/mod/gotest.tools/gotestsum@v1.8.0/internal/filewatcher/term_unix.go:50:38: undefined: tcSet
pkg/mod/gotest.tools/gotestsum@v1.8.0/internal/filewatcher/term_unix.go:58:37: undefined: tcSet
pkg/mod/gotest.tools/gotestsum@v1.8.0/internal/filewatcher/watch.go:31:18: undefined: fsnotify.NewWatcher
pkg/mod/gotest.tools/gotestsum@v1.8.0/internal/filewatcher/watch.go:99:25: undefined: fsnotify.Watcher
pkg/mod/gotest.tools/gotestsum@v1.8.0/internal/filewatcher/watch.go:197:32: undefined: fsnotify.Watcher
```

**Expected**: gotestsum is available in the defined user install directory.

Given that it is a similar missing symbol as in [this vipe issue](https://github.com/spf13/viper/issues/922) or [afero issue](https://github.com/spf13/afero/pull/210) I presume that AIX's implementation of the Filesystem is a bit different to how it works on other UNIX systems.

Not having found any other reference in the issues of gotestsum regarding AIX, I presume this hasn't come up yet. 
Is it possible to add/implement support for AIX? Happy to help there to provide any help/info where I can.

**Comment by dnephin** [comment]
I'm hoping the changes in #245 work for you. Can you build that branch and try it out? If it works I'll merge it.

Thank you!

**Comment by knmiecc** [comment]
Pulled it just now onto the AIX dev machine.
I compiled it with just `go build`, which compiled without any error.

I then went on and used it in an existing project with `<FULL/PATH/TO/THE/GIT/PROJECTS>/gotestsum/gotestsum` which worked like a charm. (It even revealed an issue with our local test setup not executing a test that gotestsum did execute :) .)

Using the flags `--format testname` also worked. Without having gone further into "all potential cases" I would say this works perfectly.

If you can think of anything else I should test, please let me know.

**Comment by dnephin** [comment]
Thanks for testing it out! That should be sufficient. I'll merge #245, and look to tag a release sometime in the next couple of weeks.
