### ISSUE TITLE
Bug: The Warning "Failed to lookup go version" Doesn't Get Suppressed, When Go Not Installed But GOVERSION is Set

### ISSUE THREAD

**Issue by erinf-wolf** [gotestyourself/gotestsum#250]
From the main readme:
"Note: If Go is not installed, or the go binary is not in PATH, the GOVERSION environment variable can be set to remove the "failed to lookup go version for junit xml" warning."

From the running without go readme https://github.com/gotestyourself/gotestsum/blob/main/docs/running-without-go.md:
```shell
export GOVERSION=1.13
gotestsum --raw-command -- test2json -t -p pkgname ./binary.test -test.v
```

^ Example code is not working for me, I still get the `WARN Failed to lookup go version for junit xml: exec: "go": executable file not found in $PATH`. Note I'm running this on a Ubuntu 20.04 Server with latest apt update (May 12 2022) .. Basically vanilla ubuntu install no extra packages.

This can be useful change, it's a concern for me since it pollutes the test results a little bit, by adding the following lines to the junit xml log

```shell
<properties>
	<property name="go.version" value="unknown"></property>
</properties>
```

**Steps to Reproduce Bug:**
- Download binary for gotestsum version 1.8.1 from release page
- Download or compile a binary for `test2json` since it's required for gotestsum to work on a compiled test binary
- Compile test binary for your go package, say name `testBinary` with some test you want to run `testName`
- On an execution environment without Go installed, set the GOVERSION environment variable and run your gotestsum command such as this
  - `sudo LOGGER=stdout ./gotestsum --format testname --junitfile logFileName.xml --raw-command -- ./test2json -t -p testPackageName ./testBinary "-test.v" "-test.run=testName"`

**Comment by dnephin** [comment]
Thank you for the detailed bug report! The `GOVERSION` env var should work for this, and there is a test covering the behaviour.

I think the problem may be that `sudo` does not pass all environment variables along. I've run into that problem before.

Could you try one of these:

* `sudo -E ...`
* `sudo --preserve-env=GOVERSION ...`
* `sudo GOVERSION=1.13 LOGGER=stdout ...`

The first two should pass along the env var, and the second would set the env var inside the sudo shell. I hope that fixes the problem for you!

**Comment by erinf-wolf** [comment]
Oh amazing! Thanks for the informative answer 😄  @dnephin 

I see my error now; I've retried executing it in one line as you suggested `sudo GOVERSION=1.13 LOGGER=stdout ...` and warning is suppressed; Closing 👍
