### ISSUE TITLE
Add Release for x86 Architectures

### ISSUE THREAD

**Issue by erinf-wolf** [gotestyourself/gotestsum#254]
Hi there, I want to be able to build `gotestsum` to be used on older Windows systems (7 32 bit, 10 32 bit) for my CI tooling 😄. I don't find any instructions on compiling on the README though, so I just download the latest release by curling from `https://github.com/gotestyourself/gotestsum/releases/latest`

Right now only arm64, arm 32 bit and amd64 architectures available .. Could the goreleaser be modified to add 386 as a target architecture to add to future releases? 

**Better yet, is there a way I can compile the code myself easily that I'm missing?** I know I can install a local version but want to be able to compile for other platforms and architectures

Similar solutions from previous issues maybe: 
- https://github.com/gotestyourself/gotestsum/issues/180
- https://github.com/gotestyourself/gotestsum/pull/245

**Comment by dnephin** [comment]
Ya, you should definitely be able to build for other platforms.

One way to do that is to install from source on the target platform with:

```
go install gotest.tools/gotestsum@latest
```
or 
```
go install gotest.tools/gotestsum@v1.8.1
```

From another platform you can cross compile with:

```
GOARCH=386 GOOS=windows go build -o gotestsum.exe .
```

I tried that and it seems to build fine for `windows/386`.  Let me know if you run into any problems and I'll do my best to help out!

**Comment by erinf-wolf** [comment]
Amazing 😄 and I assume I can build with the input `.` by navigating to the parent directory of my cloned version? gotestsum/ @dnephin

**Comment by erinf-wolf** [comment]
That may be obvious for people more seasoned with GoLang haha. Also if I don't run into problem soon then I'll close issue, thanks again for prompt help!

**Comment by erinf-wolf** [comment]
It looks to work great :) thanks so much for the help!

Closing issue
