### ISSUE TITLE
since this morning is failing when i try to install it

### ISSUE THREAD

**Issue by cosma** [gotestyourself/gotestsum#266]
Hey guys,
gotestsum is failing since this morning when I try to install it.
I also try locked on latest version v1.8.1 still not working.
I think is some dependency you have. 
I use go version 1.18
Can you please help?
Thanks!

![Screenshot 2022-07-28 at 09 49 04](https://user-images.githubusercontent.com/1668991/181451864-857ea415-6c13-4053-905f-3eb55b72e405.png)

**Comment by dnephin** [comment]
Thank you for the bug report! This is very strange. I tried `go install` both latest and `v1.8.1` and had no problems.

The dependencies list for `gotestsum` is pretty short: [go.mod](https://github.com/gotestyourself/gotestsum/blob/main/go.mod). There's no dependency on grpc for sure.

Another clue in the output is the `=== Errors` line. Thats output from `gotestsum` to indicate building some packages failed. 

I think these errors are from the second line where you run `gotestsum` to run your tests. These dependencies are likely from your go application, and `go` is trying to install them before it can compile the code and run the tests.

Hope you are able to get this sorted!

**Comment by dnephin** [comment]
Going to close this issue, since it seems the install worked and the problem was with the application being tested. Please comment on this issue if I've misunderstood and you there is still a problem here.
