### ISSUE TITLE
Compile+Release build artefacts for FreeBSD aka GOOS=freebsd

### ISSUE THREAD

**Issue by ghuntley** [gotestyourself/gotestsum#289]
👋 Howdy,

Friendly request and checking in if there's interest on your end to release builds for gotestsum that target FreeBSD to GitHub? `go install gotest.tools/gotestsum@latest && gotestsum` does indeed work on FreeBSD v13x.

# ecosystem notes

Through https://github.com/vmactions/freebsd-vm it is possible to run FreeBSD via GitHub Actions btw. 

<img width="1710" alt="CleanShot 2022-12-08 at 03 43 23@2x" src="https://user-images.githubusercontent.com/127353/206268692-3f6e1eba-e2c8-42b6-bccd-524665a5dcb7.png">

<img width="1012" alt="CleanShot 2022-12-08 at 03 52 12@2x" src="https://user-images.githubusercontent.com/127353/206268666-e0a61d3b-8934-478d-98fa-1bf86a13b622.png">

# related issues
- This all relates to upstream work over at https://github.com/coder/coder/pull/5340

**Comment by dnephin** [comment]
Hello! If someone has a need for it I would be happy to accept a PR that adds freebsd to the list of release binaries. The config for that is here: https://github.com/gotestyourself/gotestsum/blob/main/.project/goreleaser.yml

Which architectures, just amd64?
