### ISSUE TITLE
Issue new version release

### ISSUE THREAD

**Issue by obalunenko** [gotestyourself/gotestsum#294]
Hi!
Maybe it’s time to issue a new release tag? It seems a bunch of changes have arrived since the latest release:
https://github.com/gotestyourself/gotestsum/compare/v1.8.2...HEAD

@aaronlehmann @dnephin @gotestyourself-bot @vdemeester

**Comment by dnephin** [comment]
Hello! I guess it has been a while since the last release. I'll plan to do one in the next two weeks. There are a couple open PRs that I think would be good to include.

**Comment by dnephin** [comment]
Once #298 and #293 are in I think we'll be ready for a release.

**Comment by dnephin** [comment]
https://github.com/gotestyourself/gotestsum/releases/tag/v1.9.0
