### ISSUE TITLE
junitxml: Set Go version to the version used to run the tests

### ISSUE THREAD

**Issue by sagikazarmark** [gotestyourself/gotestsum#30]
Currently the go version in the JUnit report is the Go version gotestsum was built with. I should either be able to manually configure a version or gotestsum should detect it automatically.

**Comment by dnephin** [comment]
Oops, yes, good call. It assumes the binary is built by the same version running the tests, but that is not always the case.

**Comment by sagikazarmark** [comment]
Awesome! Thanks!
