### ISSUE TITLE
Allow timeout parameter to be passed to go test

### ISSUE THREAD

**Issue by samirsss** [gotestyourself/gotestsum#309]
Hi,

We currently have tests that can timeout the go test operation and hence we pass the -timeout param. I'd really appreciate it if gotestsum also takes in and passes this parameter so that we can use it for all our CIs.

Thanks!

**Comment by dnephin** [comment]
Hello! You should be able to pass a timeout as a command line argument. Any arguments after `--` are passed directly to `go test`.

```
$ gotestsum --format=testname -- -timeout=60s ./...
```


More details can be found in these [docs](https://github.com/gotestyourself/gotestsum#custom-go-test-command).

**Comment by samirsss** [comment]
Thanks for the quick response!
