### ISSUE TITLE
Output total coverage over all tested packages

### ISSUE THREAD

**Issue by mitar** [gotestyourself/gotestsum#340]
I test multiple packages in my app (code is organized into multiple internal packages) and I can get for each of them gotestsum to print coverage. But ideally I would like to get also total coverage of the whole app. There seems to be no way to do that?

**Comment by dnephin** [comment]
Thank you for your interest in `gotestsum`! This sounds like it might be a similar request to #335. 

Today `gotestsum` doesn't do anything with the coverage data. I think a tool to consume that data would be a nice addition, but I don't use coverage much personally, so it's unlikely to be something that I build.

**Comment by dnephin** [comment]
going to close this as a duplicate of #335
