### ISSUE TITLE
Release with rerun fixes?

### ISSUE THREAD

**Issue by brycekahle** [gotestyourself/gotestsum#348]
Any chance of a release with the recent fixes to the rerun logic?

**Comment by dnephin** [comment]
Yes, it would be good to do another release in August sometime. It should be possible to use the fixes pre-releaes with `go install gotest.tools/gotestsum@b8067939dbe9943cea24999f222bf725c480a3b4`.

**Comment by dnephin** [comment]
https://github.com/gotestyourself/gotestsum/releases/tag/v1.11.0 is tagged!
