### ISSUE TITLE
dotsv2: Go test stderr clobbers the outpout

### ISSUE THREAD

**Issue by howardjohn** [gotestyourself/gotestsum#356]
Example: https://asciinema.org/a/NpEIGQp4PCvKVrSxfHubhEN2T

You can see for a split second an error is emitted directly to stderr. We then overwrite it, but our "clearLines" attempt it broken since it doesn't account for it. As a result, I end up with a floating `pkg/test` indefinitely.

We will need to capture stderr and display it in the dotswriter most likely? Or something along those lines.

**Comment by dnephin** [comment]
Thank you for the bug report! Capturing the stderr seems like the right approach. We'll display it as part of the summary anyway, so we could even discard it. I opened #358 which does the discard, but I haven't had a chance to test it. 

If you confirm this forks for you I can merge it.
