### ISSUE TITLE
gotestsum slow in dind container

### ISSUE THREAD

**Issue by SaiTejaSuvvari** [gotestyourself/gotestsum#376]
I was trying to setup integration in github via github workflow.

Im building a test container inside a runner(docker container using dind image)
This test container pulls all go dependencies and starts a test using gotestsum. 
This took around 10 minutes to start the test.

Instead of doing this, I build the test package in the dind container and started the test program inside the test container. This took barely a minute. Any reason as to why this is happening?

I get that building inside a container is slow. This test program actually build binaries for other large services which took around 2-2.5 minutes. But it took around 10 minutes to start a simple test inside the container.

Is it because of the implementation of gotestsum?

**Comment by dnephin** [comment]
Hello, I am not aware of anything in `gotestsum` that would make it much slower in a docker-in-docker build. Is it possible something else change between these two setups that made it faster?

If you're able to share a link or some code that demonstrates the problem I can investigate further.

**Comment by SaiTejaSuvvari** [comment]
I think i found the difference. For the binaries built inside the container, build cache was already available which was missing for the test program. Will use the same using build cache for the test program as well. Closing the issue.
