### ISSUE TITLE
Warn on foo.go~ when using --watch

### ISSUE THREAD

**Issue by jhoffmann** [gotestyourself/gotestsum#404]
I have to assume this is a result of my Neovim running a formatter and imports checker on save, but is there any way to have gotestsum skip these messages?

![image](https://github.com/gotestyourself/gotestsum/assets/385627/3735d237-2963-4ed3-8186-33bb80b7a3e7)

**Comment by dnephin** [comment]
Hello! It looks like this was fixed back in #371, but there has not been a release since then. I'll create a release now.

**Comment by dnephin** [comment]
Should be fixed in https://github.com/gotestyourself/gotestsum/releases/tag/v1.12.0 !
