### ISSUE TITLE
Dots format outputs only on one line

### ISSUE THREAD

**Issue by silvin-lubecki** [gotestyourself/gotestsum#41]
While trying the `dots` format on the `docker/cli` unit tests, it printed everything on one line

```sh
$ GOTESTSUM_FORMAT=dots make test-unit
[some packages listed]
[cli]·····[cli/command/bundlefile]····[cli/command/checkpoint]·······[cli/command/idresolver]·····[cli/command/formatter]··················[cli/command/config]··················[cli/command]···························[cli/command/inspect]···········[cli/command/engine]···············[cli/command/manifest]············[cli/command/context]·······························[cli/command/network]·············[cli/command/container]··········↷·↷··········································································[cli/command/node]························[cli/command/plugin]······························[cli/command/registry]·············[cli/command/service/progress]····[cli/command/secret]···[cli/command/stack/formatter]·················[cli/command/stack/loader]··[cli/command/stack/swarm]·····[cli/command/swarm]·····························[cli/command/service]·····························································[cli/command/task]········[cli/command/stack]······························[cli/compose/interpolation]·····[cli/command/volume]·················[cli/compose/convert]············································[cli/compose/schema]··················[cli/command/trust]····················································································[cli/compose/loader]··········································································································[cli/compose/template]·······················[cli/config]·····················[cli/config/configfile]·············[cli/config/credentials]·············[cli/connhelper/ssh]·[cli/command/image/build]···✖✖·✖[cli/connhelper]·········[cli/command/system]········[cli/debug]···[cli/context/store]············[cli/flags]··[cli/manifest/store]·······[cli/context/kubernetes]···[internal/licenseutils]············[cli/trust]···[cmd/docker]····[internal/pkg/containerized]·[internal/containerizedengine]··········[internal/versions]·········[service/logs]·······[templates]················[cli/command/stack/kubernetes]························[opts]·····························································[cli/command/image]·↷·················✖·····↷·····································
```

I would have expected a line per package, but maybe I'm missing something with the `dots` format usage:
```sh
[cli]·····
[cli/command/bundlefile]····
[cli/command/checkpoint]·······
[cli/command/idresolver]·····
[cli/command/formatter]··················
[cli/command/config]··················
[cli/command]···························
[cli/command/inspect]···········
[cli/command/engine]···············
[cli/command/manifest]············
[cli/command/context]·······························
[cli/command/network]·············
[cli/command/container]··········↷·↷··········································································
[cli/command/node]························
...
```

**Comment by dnephin** [comment]
I was hoping to be able to do one package per line as well. When I went to implement the format I noticed that the output from `test2json` is not necessarily ordered in the way you would expect. The start package event would be sent before the previous test had finished running.

Because of the ordering you'd end up with the dots on each line not matching the tests in the package, which I found to be misleading. The problem still exists with the single line format, but at least that way it doesn't look as much like the dots necessarily match the proceeding package.

I'm not sure if that behaviour has changed since in a more recent version of Go. I believe it has to do with `go test` running multiple packages in parallel by default. I think it's probably worth revisiting to see if there is some way to make it work.

**Comment by silvin-lubecki** [comment]
> The problem still exists with the single line format, but at least that way it doesn't look as much like the dots necessarily match the proceeding package.

If I understand that correctly, it means that a test dot can be printed to another package? And so if we have a failing test, it can be printed to a wrong package, then misleading if you try to find the failing test in the wrong package?
If that is the case, I don't think the `dot` format is really useful 🤔

**Comment by dnephin** [comment]
Ya, it probably isn't. I kept it around hoping there would be some way to fix it.

I think one package per line would be possible by keeping track of which package is on which line and moving the cursor to print on that line, like how download progress clis work, but I expect that would be some work.

**Comment by silvin-lubecki** [comment]
> keeping track of which package is on which line and moving the cursor to print on that line, like how download progress clis work

Yep I thought about that too

>  but I expect that would be some work.

Sure it would 😄

**Comment by silvin-lubecki** [comment]
Should I close this issue?

**Comment by dnephin** [comment]
I think we should keep it open. It is a good idea, and maybe one day it will get implemented.

**Comment by dnephin** [comment]
I put up #79 which implements this format
