### ISSUE TITLE
Allow building of test binaries with gotestsum

### ISSUE THREAD

**Issue by fasmat** [gotestyourself/gotestsum#418]
`go test` has a neat feature where one can build a binary of all tests with `go test -c -o ./build/test` that can then be executed without using the `go test` command. Would it be possible to add this functionality to `gotestsum` as well, or alternatively have `gotestsum` run such a binary instead of `go test`?

**Comment by dnephin** [comment]
Hello! Yes that should be possible today. There's an example in the README: [Executing a compiled test binary](https://github.com/gotestyourself/gotestsum?tab=readme-ov-file#executing-a-compiled-test-binary).

**Comment by fasmat** [comment]
Never mind, it is possible to do what I wanted to do. By following this guide: https://github.com/gotestyourself/gotestsum/blob/main/.project/docs/running-without-go.md

Thanks again for pointing me in the right direction! ❤️
