### ISSUE TITLE
Slow test execution on Apple M1 Pro & M2 chip

### ISSUE THREAD

**Issue by ethicnology** [gotestyourself/gotestsum#424]
We use `gotestsum` with my colleagues, and we noticed that the execution of tests is significantly slower (ten times slower) on Apple M2 compared to the traditional `go test`. For a series of tests running on the same host, I observed the following times:

    Using gotestsum: 462.245s
    Using go test: 44.12s

**Comment by dnephin** [comment]
Thank you for  the bug report! I don't have any Apple machines that I can use to reproduce.

Can you confirm this is not an issue with M1 machines?

Can you send me the full command line you use to run `gotestsum` ? Maybe it's specific to one of the features?

**Comment by ethicnology** [comment]
In my team we use these commands:
- `time go test -p 1 -count=1 -timeout 30m ./...`
- `time gotestsum --format dots-v2 -- -p 1 -count=1 -timeout 30m ./...`

The flag `-json` has a similar runtime to `go test`, way faster than `gotestsum`. Currently, I'm using `time go test -p 1 -count=1 -timeout 30m -json -v ./... | gotestfmt` because of the speed problem, but I enjoy more the output of `gotestsum` and specially the `sum`.

I can't confirm for `M1` and `M2 Pro` chips, but in our team I can confirm for `M1 Pro` and `M2` in comparison to our GNU/linux coworkers.

**Comment by dnephin** [comment]
It may be related to the dots-v2 format. Do you see the same problem with
the default format or testname format?

**Comment by aaomidi** [comment]
FWIW I've not seen this problem on my end.

**Comment by ethicnology** [comment]
Probably related to our environment then, thank you
