### ISSUE TITLE
Disable colors on windows terminals

### ISSUE THREAD

**Issue by dnephin** [gotestyourself/gotestsum#47]
https://github.com/fatih/color/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+windows has a few issues about this. It sounds like windows terminals are detected as terminals, but do not support color, so it needs to be disabled.

I don't have a windows machine to test this. If someone does and is interested in submitting a PR, please let me know!

**Comment by ebilling** [comment]
Why not use the flag to disable color?

**Comment by dnephin** [comment]
This was most likely fixed with the change to default the noColor option to what is detected by the color library. I'm going to close for now, but we can re-open if it is still an issue.
