### ISSUE TITLE
Using gotestsum binary in jenkins pipeline

### ISSUE THREAD

**Issue by manikesh** [gotestyourself/gotestsum#55]
I am using gotestum  unix binary in my jenkins pipleline, issue is when it starts running tests  it looks for some libs related to gotestsum, since libs are not available it fails. my concern is when binary is used it should not look for required libs, we are not building the code of gotestsum, we are just using the binary. 

when same is run on local IDE, it does not look for libs, it just runs test and shared result, same is expected in pipeline as well but it fails.

Only diff is on local we use, exe and in jenkins it uses linux binary.

**Comment by dnephin** [comment]
The binary available from https://github.com/gotestyourself/gotestsum/releases is statically compiled, so it won't look for libraries. 

If the command is failing, it sounds like it's an issue with your go environment. Do you see the same errors if you run `go test -v ./...` ?

If you paste the errors you see I might be able to help solve the problem. Common problems include:
* `GOPATH` is not set correctly
* `GOROOT` is not set correctly
* `CGO_ENABLED` is not set correctly

**Comment by manikesh** [comment]
Thanks much for you reply and sorry for delay... is there is any issue with env then command "go build" should also fail but it does not, my code gets compiled and binary gets generated of my code.  I even run few specific test cases and it works well.. only when I do gotestsum it start looking for libs.. I will again go and run same command and paste the result here..

**Comment by manikesh** [comment]
humm.. surprisingly.. go test -v ./... is also trying to load same libs.. but on local even this command is working fine.. why behavior is different in different OS.. I made sure all libs are committed and available in GOPATH. what am I missing here? Also this is not meant for cicleCI rt? it will work in jenkins as well?

**Comment by dnephin** [comment]
Yes, it should work with any CI system that supports junit.xml, including Jenkins. I have heard reports from others that it works well with Jenkins.

I suspect the problem is the environment. Probably one of the environment variables I listed above, or maybe something about where go is installed.

**Comment by manikesh** [comment]
thank you... I just gave command " gotestsum . " making sure only current directory tests are executed, it worked nicely, but when I just give gotestum, looks like it tries to run all test which are part of different packages and it starts looking for libs... only query is how its working in local?

also I printed go env,  I could see CGO_ENABLED=1 in both, also gopath and goroot are set and obviously values are different.

**Comment by manikesh** [comment]
Thanks its sorted out.. though I am not able to run without current directory but I can live with it.
