### ISSUE TITLE
Coverage report duplicated in standard-quiet format

### ISSUE THREAD

**Issue by Moe-Kite** [gotestyourself/gotestsum#56]
Hi, 

First, thanks for this tool, that's pretty cool and the final summary is really nice. 

The only thing that I miss was coverage support when coverage is enabled in go test. Switching to the format `standard-quiet` solve that by printing the normal line, but in this case, the coverage report is duplicated:
```
gotestsum --format standard-quiet ./test-folder1/... ./test-folder2/... ./local-code/... -- -cover
coverage: 50.6% of statements
ok  	path/to/some/tests	0.018s	coverage: 50.6% of statements
```
I tried to get a really quick look at the code but couldn't find immediately where was the issue. 
Also, if it was possible to have coverage support in short format (just having the percentage at the end of the line if coverage is enabled), that would be magic!

Thanks in advance, 
Moe

**Comment by dnephin** [comment]
Hello, thank you for the report and your interest in `gotestsum`!

I ran `go test -json -cover` to see what was being output and I found this:

```
{"Time":"2019-06-20T18:51:29.178811583-04:00","Action":"output","Package":"gotest.tools/assert/cmp","Output":"coverage: 91.1% of statements\n"}
{"Time":"2019-06-20T18:51:29.178821431-04:00","Action":"output","Package":"gotest.tools/assert/cmp","Output":"ok  \tgotest.tools/assert/cmp\t(cached)\tcoverage: 91.1% of statements\n"}
{"Time":"2019-06-20T18:51:29.183452652-04:00","Action":"output","Package":"gotest.tools/assert","Output":"coverage: 85.2% of statements\n"}
{"Time":"2019-06-20T18:51:29.183457861-04:00","Action":"output","Package":"gotest.tools/assert","Output":"ok  \tgotest.tools/assert\t(cached)\tcoverage: 85.2% of statements\n"}
```

Which I think is strange, but it does explain why the coverage output is being printed twice. `test2json` is sending two events which include the same text in the output. I took a quick look on the go/golang issue tracker, but I don't see any reports of this problem. I'm not sure if it's a bug or not. I created https://github.com/golang/go/issues/32717 to find out.

The duplicate output could be filtered out with some hacky string matching, but I'll wait on a response from the Go team first.

I think adding it to the default `short`  format might be easier to do. I'll give that a shot.

**Comment by dnephin** [comment]
I think #57 should address both changes. It ended up being easy enough. Let me know if that works for you.
