### ISSUE TITLE
Add --max-failure=count flag to exit early

### ISSUE THREAD

**Issue by dnephin** [gotestyourself/gotestsum#6]
When running in CI it is sometimes desirable to exit before all tests are run so that resources aren't wasted running against code that is obviously broken.

```
--max-failure count   stop execution after x failures
```

**Comment by lox** [comment]
Looks like `go test` now has `-failfast`. What if we just exposed that?

> The new go test -failfast flag disables running additional tests after any test fails. Note that tests running in parallel with the failing test are allowed to complete.

**Comment by dnephin** [comment]
Nice! Good call. I missed that addition in [the go1.10 patch notes](https://golang.org/doc/go1.10#test).

Since we can already access all the existing `go test` flags using `--` I'm going to close this one.

Thanks for suggestion!

For any future reads comign to this thread not familiar with the syntax, this should work:

```
gotestsum  -- -failfast ./...
```

**Comment by lox** [comment]
Oh neat, I didn't realize that was a thing!
