### ISSUE TITLE
Show benchmark output in verbose formats

### ISSUE THREAD

**Issue by nhooyr** [gotestyourself/gotestsum#62]
Right now unless you're using standard-verbose, running benchmarks at the same time as tests causes the benchmark output to be hidden. It'd be nice if it was parsed and shown in some nice colours.

**Comment by nhooyr** [comment]
It doesn't need to show bench output always, maybe just make sure if a benchmark fails, the output is shown. I'm only running benchmarks for coverage/race detection purposes with `go test`.

**Comment by nhooyr** [comment]
Ah, looks like gotestsum doesn't even run benchmarks at the same time as tests. It just skips the benchmarks entirely.

**Comment by nhooyr** [comment]
Ah I believe it already does this, if a benchmark fails the output will be shown which is fine for my use case for now but it'd be nice to also show the output in a nice summary.

**Comment by dnephin** [comment]
Thanks for the report!

It looks like the `standard-verbose` format is the only one that works correctly. `standard-quiet` hides more output than `go test`, and both `short-verbose` and `short` formats don't show any output for benchmarks unless they fail.

I think it should make sense to show the output, at least in the verbose formats.

**Comment by dnephin** [comment]
I took a look at the test2json output, and it does not appear to be working the way it is documented in https://golang.org/cmd/test2json/

Here's an example line:
```
"Time":"2019-08-25T14:14:19.671470609-04:00",
"Action":"output",
"Package":".../pkg/cmd",
"Test":"TestNearTimeoutWarning",
"Output":"BenchmarkCmdRunnerBaseline/testdata/1kL-500C.bench-8
```

The action should be `bench` not `output`, and the `Test` should be the name of the benchmark, not the last test that ran.

It seems there are bugs in the `go test -json` output which might make this hard to implement. I haven't found a related issue on the go bug tracker yet. That might be the first step required to fix this.

**Comment by nhooyr** [comment]
Going to close as it has been a while and I'm not sure if this is relevant anymore.
