### ISSUE TITLE
Please clarify the copyright for this package

### ISSUE THREAD

**Issue by elboulangero** [gotestyourself/gotestsum#65]
Dear upstream,

I'd like to package gotestsum for Debian, however for that I would need a clear copyright mention somewhere, as for now I don't know who is the copyright holder.

See for example this commit: https://github.com/containerd/fifo/pull/15/files

Thanks!

**Comment by dnephin** [comment]
Hello! Thank you for your offering to package up this tool for Debian.

I've added a NOTICE file in #67 

Please let me know if you need anything else. Thank you!

**Comment by elboulangero** [comment]
That's perfect, thanks!
