### ISSUE TITLE
test2json incorrectly attributes output to a subtest, resulting in missing test failure output

### ISSUE THREAD

**Issue by dnephin** [gotestyourself/gotestsum#66]
Upstream issue: https://github.com/golang/go/issues/29755

Symptoms: `gotestsum` reports that a test failed, but does not show any failure output in the summary.

Workarounds: Use the `standard-verbose` format.

Possibly solution: If  the bug is not fixed upstream then one solution would be to print the output for the entire top level test, instead of just the output for the subtest.

**Comment by dnephin** [comment]
https://github.com/golang/go/pull/34419
https://go-review.googlesource.com/c/go/+/196617

**Comment by dnephin** [comment]
The fix for this was included in go1.15, so I think it's probably time to close this issue.

**Comment by edaniels** [comment]
Without using the workaround, I still see this issue with standard arguments. Including --debug has it sometimes show up.

**Comment by dnephin** [comment]
Thanks for the report! Would you mind opening a new issue with info about the Go version used, and if possible steps to reproduce?

From the linked pull request it sounds like maybe it has to do with `go test -race` output?

**Comment by edaniels** [comment]
Filed https://github.com/gotestyourself/gotestsum/issues/310
