### ISSUE TITLE
Configure verbosity of failing tests separately from passing tests

### ISSUE THREAD

**Issue by wendorf** [gotestyourself/gotestsum#72]
When running longer test suites, I don't want to wait for the suite to finish to see my failures. Currently the only way to get this behavior is to use a `-verbose` format, but then I see all of my passing tests, which makes it hard to see the (comparatively) smaller number of failures.

I would like to be able to specify whether to show passing tests verbosely independently of failing tests. Something like `gotestsum --format short --verbose-failures`.

**Comment by dnephin** [comment]
Thanks for the feature request! I've opened PR #73 which adds a new format with that behaviour. I'd prefer to keep all the formatting behaviour on a single flag, so I opted to add a new format instead of a new flag. 

Let me know if this new format works for your case you've described.

**Comment by wendorf** [comment]
Works great! Thank you!
