### ISSUE TITLE
Add post-run hook to support sending desktop notifications

### ISSUE THREAD

**Issue by dnephin** [gotestyourself/gotestsum#74]
Thanks to @glenjamin for the idea.

Instead of publishing notifications directly I'd like to add support for executing a script that is passed all of the necessary details, and can handle any type of notification.

The script should be called with env vars which contain a summary of the run, and a json blob could be passed to stdin to provide full details about any errors.

Such a feature might look something like this:

```
export GOTESTSUM_POST_RUN_SCRIPT=./scripts/notify-test-results.sh
gotestsum
```

Env vars:
```
TEST_TOTAL=100
TEST_FAILED=2
TEST_SKIPPED=5
TEST_ERRORS=0
```

I'm not sure how to encode more details. The junixml format might work, but is probably not the easiest format to integrate. A custom JSON document might work but will be more involved to maintain. 

Maybe env vars will work for the first version.

**Comment by glenjamin** [comment]
When I use these I tend to have my editor window focused, and my terminal running tests hidden - so ideally the notification should get enough data exposed to be able to include some details about the failure:

- files that failed to compile
- the compilation errors
- tests that failed
- files and line numbers of failed tests

**Comment by dnephin** [comment]
Started some work in #76 which I think would enable a basic notification.

File and line numbers is not something that is currently parsed. Test names are easy enough, but the file and line numbers are for the failed checks not for the tests cases themselves.

**Comment by glenjamin** [comment]
I had a little play around with this, had to switch to a shell exec to be able to handle multiple arguments to the hook command well:

https://github.com/gotestyourself/gotestsum/commit/4728f41e79edb14bf85df67426155f7ec0f67f9e

<img width="358" alt="Screenshot 2019-11-03 at 12 45 39" src="https://user-images.githubusercontent.com/151272/68085347-f9da4b00-fe37-11e9-9ab3-13be0b3b44bd.png">
<img width="363" alt="Screenshot 2019-11-03 at 12 45 26" src="https://user-images.githubusercontent.com/151272/68085349-f9da4b00-fe37-11e9-87dc-d73122766833.png">

**Comment by dnephin** [comment]
Thanks for your work on this! I've merged the original PR which adds the new command line flag, and opened #116 for possible next steps.

I'll also open a PR now for adding it to the documentation in the next release.
