### ISSUE TITLE
Missing logs when test panic in go 1.14

### ISSUE THREAD

**Issue by jsdidierlaurent** [gotestyourself/gotestsum#95]
Hello!

I recently update my project to go 1.14 and when my test panic i have no output (just exit 1).

![image](https://user-images.githubusercontent.com/11354381/76539124-9e246c00-6480-11ea-9617-0b6fdd1838b2.png)

With `gotestsum --format short`
![image](https://user-images.githubusercontent.com/11354381/76539278-d9269f80-6480-11ea-8131-d8ada12d1adb.png)

With `go test ./...`
![image](https://user-images.githubusercontent.com/11354381/76539380-fe1b1280-6480-11ea-9d7e-ced1db54e538.png)

If you need small project to reproduce, tell me i can create it.

Thanks !

**Comment by dnephin** [comment]
Thanks for the report! We traced this down in #94 . It sounds like it will be fixed in go1.14.1

**Comment by jsdidierlaurent** [comment]
Ok! Thanks ^^

**Comment by dnephin** [comment]
Go 1.14.1 was released a couple days ago and it appears to have fixed this problem. I'd like to keep this open for a while as others upgrade, to make it easier for them to find the solution.
