### ISSUE TITLE
Execution time is 0.00s when using gotestsum with binary.

### ISSUE THREAD

**Issue by alufrew** [gotestyourself/gotestsum#96]
I'am trying to use gotestsum in following way:
gotestsum -f short-verbose  --raw-command -- go tool test2json -p test ./test/run-tests -test.v

Test are running without problem but time execution of any test is 0.00s. F.e.:
PASS test.TestSomeFoo (0.00s)

Overall test execution time is reported properly. Am I missing something?

**Comment by dnephin** [comment]
Hello, thank you for your interest in `gotestsum`!

The overall test execution time is calculated by subtracting the start time from the end time. It should always be about the same value as reported by `time gotestsum`. 

The elapsed time for each test is taken from the `TestEvent` JSON produced by `go tool test2json`. 

I suspect what is happening is that the package test execution is cached. As of [gotestsum v0.4.0](https://github.com/gotestyourself/gotestsum/releases/tag/v0.4.0)  `gotestsum` will print `(cached)` on the package line, to indicate that is what is happening.

The package line should look like `PASS  pkgname (cached)`. Is that what is happening?

You can tell `go test` to not use the cache by adding the `-count 1` flag after `-test.v`.

**Comment by alufrew** [comment]
Hi. Thank you for your response.

It seems cache is not the case. As of your advise tried following line:
gotestsum -f short-verbose  --raw-command -- go tool test2json -p test ./test/run-tests -test.v -test.count 1

Result is for one test case: PASS test.TestResetPasswordSuccess (0.00s)

**Comment by dnephin** [comment]
What value are you expecting for the elapsed time of the test? Is it possible the test is running in less than 1ms?

**Comment by alufrew** [comment]
No. When I run just:
gotestsum -f short-verbose 
the result will be PASS test.TestResetPasswordSuccess (2.37s) in this case. 
Just to make sure that tests are not running somehow faster when put in binary tried to set 10 seconds wait in test. Test is running visibly longer but still 0.00s execution time is reported.

**Comment by dnephin** [comment]
Oh, that is very strange! To debug this problem I think we should look at the json output by `test2json`.

Could you paste the relevant line from the output of `go tool test2json -p test ./test/run-tests -test.v` and `go test -json ./...` ?

The line should be the one that has `"Action":"pass"` and `"Test":"TestResetPasswordSuccess"`. If it's not too much  output all of the lines for `TestResetPasswordSuccess` might be helpful to debug.

**Comment by alufrew** [comment]
Hi. TestResetPasswordSuccess is quite long as there are many steps. So I made one api call test example for simplicity. I only changed project name here. Made binary via  go test ./test -c -o run-tests. And made 3 runs.
Results are following:

gotestsum -f short-verbose  --raw-command -- go tool test2json -p test ./test/run-tests -test.v
PASS test.TestSignUpSuccess (0.00s)
PASS test

go tool test2json -p test ./test/run-tests -test.v 
{"Action":"run","Package":"test","Test":"TestSignUpSuccess"}
{"Action":"output","Package":"test","Test":"TestSignUpSuccess","Output":"=== RUN   TestSignUpSuccess\n"}
{"Action":"output","Package":"test","Test":"TestSignUpSuccess","Output":"2020/03/25 10:39:16 https://test.server/v1/user {{\"email\":\"cd1bb2a5-e717-4c82-841d-f75271cb7c3f@weareclario.com\",\"password\":\"SBuw5362\",\"device_id\":\"kj7e97R2\",\"name\":\"LpYmn QIcnmnB\",\"consents\":{\"app_statistics\":false,\"marketing_name\":false,\"marketing_emails\":false}}}\n"}
{"Action":"output","Package":"test","Test":"TestSignUpSuccess","Output":"--- PASS: TestSignUpSuccess (0.47s)\n"}
{"Action":"pass","Package":"test","Test":"TestSignUpSuccess"}
{"Action":"output","Package":"test","Output":"PASS\n"}
{"Action":"pass","Package":"test"}

go test -json ./...
{"Time":"2020-03-25T10:39:44.016219+02:00","Action":"run","Package":"gitlab/repo/test-project/test","Test":"TestSignUpSuccess"}
{"Time":"2020-03-25T10:39:44.016267+02:00","Action":"output","Package":"gitlab/repo/test-project/test","Test":"TestSignUpSuccess","Output":"=== RUN   TestSignUpSuccess\n"}
{"Time":"2020-03-25T10:39:44.017039+02:00","Action":"output","Package":"gitlab/repo/test-project/test","Test":"TestSignUpSuccess","Output":"2020/03/25 10:39:44 https://test.server/v1/user {{\"email\":\"3ba536e8-781c-4890-8260-d0fd888d3042@weareclario.com\",\"password\":\"CMWF1556\",\"device_id\":\"XWi4MDCc\",\"name\":\"icxYS aeeSqUI\",\"consents\":{\"app_statistics\":false,\"marketing_name\":false,\"marketing_emails\":false}}}\n"}
{"Time":"2020-03-25T10:39:44.519553+02:00","Action":"output","Package":"gitlab/repo/test-project/test","Test":"TestSignUpSuccess","Output":"--- PASS: TestSignUpSuccess (0.50s)\n"}
{"Time":"2020-03-25T10:39:44.519586+02:00","Action":"pass","Package":"gitlab/repo/test-project/test","Test":"TestSignUpSuccess","Elapsed":0.5}
{"Time":"2020-03-25T10:39:44.519596+02:00","Action":"output","Package":"gitlab/repo/test-project/test","Output":"PASS\n"}

**Comment by dnephin** [comment]
Thank you for adding the log output!

I can see that `Elapsed` is in the JSON when run with `go test -json`, but not when running `go tool test2json` directly. This is really strange.

The only other flag I see is `-t` which adds the timestamps. Any change that adding that flag makes it work?  `go tool test2json -t -p test ...`

It does seem to be a bug with `test2json` not parsing the elapsed time out of the output correctly in some cases.

**Comment by alufrew** [comment]
Oh. -t option helped. Now, when i use command lower time is shown correctly. Thanks a lot.
gotestsum -f short-verbose --raw-command -- go tool test2json -t -p test ./test/run-tests -test.v

**Comment by dnephin** [comment]
Excellent, I'm surprised, but glad that worked!

I'm going to re-open the issue so that we can update https://github.com/gotestyourself/gotestsum/blob/master/docs/running-without-go.md to include the `-t` flag.
