### ISSUE TITLE
Execution time is slower with go 1.14

### ISSUE THREAD

**Issue by jsdidierlaurent** [gotestyourself/gotestsum#97]
Hello !

I don't understand why, but when i run my tests with gotestsum and go 1.14, it's slower than with go 1.13.

### G0 1.14
![image](https://user-images.githubusercontent.com/11354381/77663803-c41c3700-6f7d-11ea-9fc5-e10b3faf6e2f.png)

### Go 1.13
![image](https://user-images.githubusercontent.com/11354381/77664034-0e9db380-6f7e-11ea-998e-37d7fa8e8e6e.png)

If you need more information i can help :smile:

**Comment by dnephin** [comment]
Oh wow, 33 seconds? That is much slower. I haven't noticed this myself, but it is possible I missed it. I'll have a look.

**Comment by jsdidierlaurent** [comment]
6,583s not 33s (time command return total of each cpu) look at the end 🙂

**Comment by dnephin** [comment]
I tried to reproduce this with the https://github.com/monitoror/monitoror test suite. I used [the binary from the 0.4.1 release](https://github.com/gotestyourself/gotestsum/releases/tag/v0.4.1), and I used docker images for go1.13/go1.14, both the alpine variant with CGO disabled, and the default variant with CGO enabled. Docker was running on a linux host, so no Docker4Mac virtualization.

In all cases it took about 32-35s on the first run to download modules and run all tests, and about 0.8-0.9s for a cached run. There was some variance between runs, but there were go1.13 runs that were on the higher end at 1s, and go1.14 runs that were on the lower end, so nothing consistent between versions. I was not able to reproduce those results.

When you were running `gotestsum` on the different versions of Go, were you always using the same compiled binary, or did you compile it with the version of Go that was being used to run the tests?

Are you able to reproduce this behaviour running the same test suite on other machines? Was it on an OSX host? How consistently are you able to reproduce the slower test runs? Can you reproduce the behaviour with other test suites as well, or is it this one project?

**Comment by jsdidierlaurent** [comment]
Hum, i will try with other host and i will reinit my setup.

Thanks a lot for trying to help me ^^

**Comment by jsdidierlaurent** [comment]
Hello again!

I try to test this with a fresh install of ubuntu with go 1.14.1 and master version og gotestsum and i always have performance issue.

But I wonder if the problem does not come from the architecture of my project.
Did you try with develop branch of monitoror ?

I change lot of this in develop and i experiment this issue only with my new architecture.

**Comment by dnephin** [comment]
I tested with https://github.com/monitoror/monitoror/commit/da09cc35b953d887f6d56d7d7a9b19e883f774eb, which was the HEAD of devlop at the time

**Comment by jsdidierlaurent** [comment]
I don't know why, but the problem seems solved. I change nothing on my go / gotestsum setting ... and my tests run in less than 2s.

I don't know why :rage: 

But the problem seems to come from me and not from the project

Thank a lot for trying to help me ^^
